api_extraction:
  header_dir: /home/lanjiachen/DGF/testdata/cJSON
  include_dirs:
    - /home/lanjiachen/DGF/testdata/cJSON
  extracted_api_json: /home/lanjiachen/DGF/src/data/extracted_api.json

prompt_generation:
  output_dir: /home/lanjiachen/DGF/src/data/seed_prompts
  samples: 2
  num_funcs: 5

feedback_iteration:
  output_dir: /home/lanjiachen/DGF/src/data/feedback_results
  samples_per_round: 2

validator:
  clang_path: clang-14
  include_dirs:
    - /home/lanjiachen/DGF/testdata/cJSON
  lib_dir: /home/lanjiachen/DGF/testdata/cJSON/build
  libs:
    - cjson
    - cjson_utils
